version: '3.3'
services:
  jenkins:
    build: .
    ports:
      - "49001:8080"
    volumes:
      - ./jenkins:/var/jenkins_home

  selenium-hub:
    image: selenium/hub:3.6.0
    ports:
      - "49002:4444"
  chrome:
    image: selenium/node-chrome:3.6.0
    links:
      - selenium-hub:hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444

